name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Set up Koka
        uses: koka-community/setup-koka@v1
        with:
          koka_ref: "dev"
          packages: ""
      - name: Run tests
        run: |
          koka --verbose=0 --console=ansi -e std/test/detect
